# Generated by Django 3.2.7 on 2021-09-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='disabilities',
            field=models.TextField(default='Not Added Yet', null=True),
        ),
    ]
