# Generated by Django 3.2.7 on 2021-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0002_alter_userprofile_disabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='undergoing_treatments',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disabilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
