# Generated by Django 3.2.7 on 2021-09-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0003_auto_20210914_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name_in_case_of_emergency',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
