# Generated by Django 3.2.7 on 2021-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0005_auto_20210915_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
