# Generated by Django 3.2.7 on 2021-09-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0007_auto_20210916_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_address', models.TextField(max_length=200, null=True)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_qr.userprofile')),
            ],
        ),
    ]
