# Generated by Django 3.2.7 on 2021-09-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0008_deliversticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliversticker',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='basic_qr.userprofile'),
        ),
    ]
