# Generated by Django 3.2.7 on 2021-09-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0010_auto_20210920_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliversticker',
            name='name',
        ),
    ]
