# Generated by Django 3.2.7 on 2021-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0011_remove_deliversticker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliversticker',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
