# Generated by Django 3.2.7 on 2021-09-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_qr', '0013_alter_userprofile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(help_text='*', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_name_in_case_of_emergency',
            field=models.CharField(help_text='*', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(help_text='*', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number_in_case_of_emergency',
            field=models.CharField(help_text='*', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_cms',
            field=models.IntegerField(help_text='*', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(help_text='*', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight_kgs',
            field=models.FloatField(help_text='*', null=True),
        ),
    ]
